silence macos warning
on macos we are running into the following warning when trying to run
the system autodetection:

```
/Applications/Xcode11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:61:15:
fatal error: 'string.h' file not
      found
              ^~~~~~~~~~
```

it seems that the compiler cannot find the sdk root, so the c++ headers
cannot find the c headers. we therefore add the macos sdk path manually